-- AlterTable
ALTER TABLE "Course" ADD COLUMN     "courseId" TEXT NOT NULL DEFAULT 'default-course-id',
ADD COLUMN     "endDate" TIMESTAMP(3) NOT NULL DEFAULT '2100-01-01 00:00:00 +00:00',
ADD COLUMN     "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
